# Generated by Django 4.2.4 on 2023-09-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClase19', '0002_categoria_producto_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
